const properties = [
  {
    id: "CM-0001",
    title: "Wiang Ping Mansion Room 1110",
    city: "Chiang Mai",
    type: "Condo",
    deal: "Sale",
    price: "2.59 MB",
    bedrooms: "1 Bedroom",
    bathrooms: "1 Bathroom",
    area: "36 sq.m.",
    description: "Near MAYA only 200 m, 11th floor, renovated, foreign quota, Airbnb allowed, free transfer.",
    images: [
      "images/wiang-ping-1110-1.jpg",
      "images/wiang-ping-1110-2.jpg",
      "images/wiang-ping-1110-3.jpg"
    ]
  },
  {
    id: "CM-0002",
    title: "JC Hill Place Room 909",
    city: "Chiang Mai",
    type: "Condo",
    deal: "Sale",
    price: "2.39 MB",
    bedrooms: "1 Bedroom",
    bathrooms: "1 Bathroom",
    area: "32.09 sq.m.",
    description: "Jed Yod location, foreign quota, renovated, suitable for living or investment.",
    images: [
      "images/jc-hill-909-1.jpg",
      "images/jc-hill-909-2.jpg",
      "images/jc-hill-909-3.jpg"
    ]
  },
  {
    id: "CM-0003",
    title: "Hillside 3 Nimman Room 236",
    city: "Chiang Mai",
    type: "Condo",
    deal: "Sale",
    price: "2.89 MB",
    bedrooms: "1 Bedroom",
    bathrooms: "1 Bathroom",
    area: "35 sq.m.",
    description: "Nimman Soi 8, large balcony, foreign quota, Airbnb allowed, free transfer.",
    images: ["images/hillside3-236-1.jpg"]
  },
  {
    id: "CM-0004",
    title: "Rawiwari Residence 1 Bedroom",
    city: "Chiang Mai",
    type: "Condo",
    deal: "Sale",
    price: "6.59 MB",
    bedrooms: "1 Bedroom",
    bathrooms: "1 Bathroom",
    area: "71.36 sq.m.",
    description: "Nimman 15, foreign quota, Airbnb allowed, renovated, premium investment location.",
    images: ["images/rawiwari-1br-1.jpg"]
  },
  {
    id: "CM-0005",
    title: "Rawiwari Residence 2 Bedroom",
    city: "Chiang Mai",
    type: "Condo",
    deal: "Sale",
    price: "6.59 MB",
    bedrooms: "2 Bedrooms",
    bathrooms: "1 Bathroom",
    area: "76.26 sq.m.",
    description: "Nimman 15, 2-bedroom unit, foreign quota, Airbnb allowed, renovated.",
    images: ["images/rawiwari-2br-1.jpg"]
  },
  {
    id: "CM-0006",
    title: "Pool Villa Don Chan",
    city: "Chiang Mai",
    type: "House",
    deal: "Sale",
    price: "9.89 MB",
    bedrooms: "4 Bedrooms",
    bathrooms: "4 Bathrooms",
    area: "74 sq.w.",
    description: "Private pool villa with saltwater pool, jacuzzi, modern luxury design in Don Chan area.",
    images: ["images/pool-villa-donchan-1.jpg"]
  },
  {
    id: "CM-0007",
    title: "New House Nong Hoi",
    city: "Chiang Mai",
    type: "House",
    deal: "Sale",
    price: "4.9 MB",
    bedrooms: "4 Bedrooms",
    bathrooms: "3 Bathrooms",
    area: "85.7 sq.w.",
    description: "New house near Varee School, Montfort College and Big C Don Chan. Free transfer.",
    images: ["images/nong-hoi-house-1.jpg"]
  },
  {
    id: "CM-0008",
    title: "Land Nong Hoi",
    city: "Chiang Mai",
    type: "Land",
    deal: "Sale",
    price: "1.8 MB",
    bedrooms: "-",
    bathrooms: "-",
    area: "108.8 sq.w.",
    description: "Land near Montfort and Varee, about 5 minutes to airport, good for residence or investment.",
    images: ["images/nong-hoi-land-1.jpg"]
  },
  {
    id: "CM-0009",
    title: "Karnkanok Ville 12 House",
    city: "Chiang Mai",
    type: "House",
    deal: "Rent",
    price: "36,000 THB/month",
    bedrooms: "4 Bedrooms",
    bathrooms: "4 Bathrooms",
    area: "220 sq.m.",
    description: "Saraphi house for rent, fully furnished, near international schools, no pets.",
    images: ["images/karnkanok-12-1.jpg"]
  },
  {
    id: "CM-0010",
    title: "Siwalee Sankampang House",
    city: "Chiang Mai",
    type: "House",
    deal: "Sale",
    price: "6.1 MB",
    bedrooms: "4 Bedrooms",
    bathrooms: "5 Bathrooms",
    area: "119.5 sq.w.",
    description: "Land & Houses project, tenant income 40,000 THB/month, suitable for investor.",
    images: ["images/siwalee-sankampang-1.jpg"]
  },
  {
    id: "BKK-0001",
    title: "Supalai Veranda Rama 9",
    city: "Bangkok",
    type: "Condo",
    deal: "Sale",
    price: "3.29 MB",
    bedrooms: "1 Bedroom",
    bathrooms: "1 Bathroom",
    area: "37.5 sq.m.",
    description: "Condo with tenant, rental income 12,000 THB/month. Owner finance available.",
    images: ["images/supalai-veranda-rama9-1.jpg"]
  },
  {
    id: "BKK-0002",
    title: "Supalai Elite Sathorn-Suanplu",
    city: "Bangkok",
    type: "Condo",
    deal: "Sale",
    price: "12.99 MB",
    bedrooms: "2 Bedrooms",
    bathrooms: "2 Bathrooms",
    area: "94.8 sq.m.",
    description: "Luxury condo with tenant, rental income 45,000 THB/month, premium Sathorn location.",
    images: ["images/supalai-elite-sathorn-1.jpg"]
  },
  {
    id: "BKK-0003",
    title: "The Tree Sukhumvit 71 - Ekkamai",
    city: "Bangkok",
    type: "Condo",
    deal: "Rent",
    price: "Reserved",
    bedrooms: "1 Bedroom + Multipurpose Room",
    bathrooms: "1 Bathroom",
    area: "34.57 sq.m.",
    description: "Fully furnished condo near BTS Phra Khanong. Reserved with deposit.",
    images: ["images/the-tree-sukhumvit71-1.jpg"]
  },
  {
    id: "PL-0001",
    title: "Dusittra Ville Phitsanulok",
    city: "Phitsanulok",
    type: "House",
    deal: "Sale / Rent",
    price: "6.9 MB / 17,000 THB/month",
    bedrooms: "3 Bedrooms",
    bathrooms: "3 Bathrooms",
    area: "97.6 sq.w.",
    description: "House in Phitsanulok. Owner finance available. Cash buyer discount possible.",
    images: ["images/dusittra-ville-1.jpg"]
  },
  {
    id: "PL-0002",
    title: "Ban Khlong Shophouse 2 Units",
    city: "Phitsanulok",
    type: "Commercial",
    deal: "Rent",
    price: "30,000 THB/month",
    bedrooms: "-",
    bathrooms: "-",
    area: "2 Shophouses",
    description: "Two 3.5-floor shophouses near Ban Khlong Market, opposite Dilokphan, close to Dinosaur Market.",
    images: ["images/ban-khlong-shophouse-1.jpg"]
  },
  {
    id: "PL-0003",
    title: "Commercial Building After Ban Khlong Market",
    city: "Phitsanulok",
    type: "Commercial",
    deal: "Sale / Rent",
    price: "2.5 MB / unit",
    bedrooms: "-",
    bathrooms: "-",
    area: "16 sq.w.",
    description: "Commercial buildings behind Ban Khlong Market. Sale or rent available.",
    images: ["images/ban-khlong-building-1.jpg"]
  },
  {
    id: "PJ-0001",
    title: "Thanawan Ruedee Project",
    city: "Phichit",
    type: "House",
    deal: "Sale",
    price: "1.95 MB",
    bedrooms: "4 Bedrooms",
    bathrooms: "2 Bathrooms",
    area: "64.4 - 86.4 sq.w.",
    description: "New house project in Mueang Phichit. Booking only 5,000 THB. Free document support until loan approval.",
    images: ["images/thanawan-ruedee-1.jpg"]
  },
  {
    id: "PJ-0002",
    title: "City House Navathani Soi",
    city: "Phichit",
    type: "House",
    deal: "Sale",
    price: "3.79 MB",
    bedrooms: "4 Bedrooms",
    bathrooms: "2 Bathrooms",
    area: "56 sq.w.",
    description: "Two-storey city house in Mueang Phichit, good budget under 4 MB.",
    images: ["images/navathani-house-1.jpg"]
  },
  {
    id: "PJ-0003",
    title: "Srimala Villa Shophouse",
    city: "Phichit",
    type: "Commercial",
    deal: "Sale",
    price: "3.0 MB",
    bedrooms: "2 Bedrooms",
    bathrooms: "3 Bathrooms",
    area: "4 x 15 m",
    description: "Three-storey shophouse at Srimala Villa gate, good for business or investment.",
    images: ["images/srimala-shophouse-1.jpg"]
  },
  {
    id: "CM-0011",
    title: "A Park Plaza Business Park",
    city: "Chiang Mai",
    type: "Commercial",
    deal: "Sale",
    price: "180 MB",
    bedrooms: "-",
    bathrooms: "-",
    area: "2-3-1.9 Rai",
    description: "Business Park project in Chiang Mai with more than 50 shops. Prime investment opportunity.",
    images: ["images/a-park-plaza-1.jpg"]
  }
];
