const properties = [
  {
    "id": "CM-0001",
    "title": "Srithana 2 Huay Kaew Room 813 (8th Floor Corner Unit)",
    "city": "Chiang Mai",
    "type": "Condo",
    "deal": "Sale",
    "status": "Available",
    "price": "6.19 MB",
    "bedrooms": "2 Bedrooms",
    "bathrooms": "2 Bathrooms",
    "area": "87.5 sqm",
    "room": "Room 813",
    "floor": "8th Floor  Corner Unit",
    "map": "https://maps.app.goo.gl/R7VDGsfYJJFLoz4U8",
    "description": "Srithana 2 Huay Kaew Room 813 (8th Floor Corner Unit). 2 Bedrooms | 2 Bathrooms. Area 87.5 sqm. Room 813 8th Floor  Corner Unit.",
    "highlights": [
      "2 Bedrooms",
      "2 Bathrooms",
      "87.5 sqm",
      "8th Floor  Corner Unit",
      "Room 813"
    ],
    "images": [
      "images/srithana-2-huay-kaew-1.jpg",
      "images/srithana-2-huay-kaew-2.jpg",
      "images/srithana-2-huay-kaew-3.jpg",
      "images/srithana-2-huay-kaew-4.jpg",
      "images/srithana-2-huay-kaew-5.jpg",
      "images/srithana-2-huay-kaew-6.jpg",
      "images/srithana-2-huay-kaew-7.jpg",
      "images/srithana-2-huay-kaew-8.jpg",
      "images/srithana-2-huay-kaew-9.jpg",
      "images/srithana-2-huay-kaew-10.jpg",
      "images/srithana-2-huay-kaew-11.jpg",
      "images/srithana-2-huay-kaew-12.jpg",
      "images/srithana-2-huay-kaew-13.jpg",
      "images/srithana-2-huay-kaew-14.jpg",
      "images/srithana-2-huay-kaew-15.jpg",
      "images/srithana-2-huay-kaew-16.jpg",
      "images/srithana-2-huay-kaew-17.jpg",
      "images/srithana-2-huay-kaew-18.jpg",
      "images/srithana-2-huay-kaew-19.jpg",
      "images/srithana-2-huay-kaew-20.jpg"
    ]
  },
  {
    "id": "CM-0002",
    "title": "103 Condominium 3 Suk Kasem Soi Room 609 (6th Floor)",
    "city": "Chiang Mai",
    "type": "Condo",
    "deal": "Sale",
    "status": "Available",
    "price": "4.7 MB",
    "bedrooms": "2 Bedrooms",
    "bathrooms": "-",
    "area": "63.5 sq.m.",
    "room": "Room 609",
    "floor": "6th Floor",
    "map": "https://maps.app.goo.gl/oWSjiCTVGQxvH4aHA?g_st=ac",
    "description": "103 Condominium 3 Suk Kasem Soi Room 609 (6th Floor). 2 Bedrooms. Area 63.5 sq.m. Room 609 6th Floor.",
    "highlights": [
      "2 Bedrooms",
      "63.5 sq.m.",
      "6th Floor",
      "Room 609"
    ],
    "images": [
      "images/103-condo-3-1.jpg",
      "images/103-condo-3-2.jpg",
      "images/103-condo-3-3.jpg",
      "images/103-condo-3-4.jpg",
      "images/103-condo-3-5.jpg",
      "images/103-condo-3-6.jpg",
      "images/103-condo-3-7.jpg",
      "images/103-condo-3-8.jpg",
      "images/103-condo-3-9.jpg",
      "images/103-condo-3-10.jpg",
      "images/103-condo-3-11.jpg",
      "images/103-condo-3-12.jpg",
      "images/103-condo-3-13.jpg",
      "images/103-condo-3-14.jpg",
      "images/103-condo-3-15.jpg",
      "images/103-condo-3-16.jpg",
      "images/103-condo-3-17.jpg",
      "images/103-condo-3-18.jpg",
      "images/103-condo-3-19.jpg",
      "images/103-condo-3-20.jpg"
    ]
  },
  {
    "id": "CM-0003",
    "title": "Ravvaree Residence Nimman Soi 15 Room 301 (3th Floor)",
    "city": "Chiang Mai",
    "type": "Condo",
    "deal": "Sale",
    "status": "Available",
    "price": "6.59 MB",
    "bedrooms": "2 Bedrooms",
    "bathrooms": "-",
    "area": "76.26 sq.m.",
    "room": "Room 301",
    "floor": "3th Floor",
    "map": "https://maps.app.goo.gl/Hcpno7c57fefWAnYA",
    "description": "Ravvaree Residence Nimman Soi 15 Room 301 (3th Floor). 2 Bedrooms. Area 76.26 sq.m. Room 301 3th Floor.",
    "highlights": [
      "2 Bedrooms",
      "76.26 sq.m.",
      "3th Floor",
      "Room 301"
    ],
    "images": [
      "images/ravvaree-residence-nimman-soi-15-1.jpg",
      "images/ravvaree-residence-nimman-soi-15-2.jpg",
      "images/ravvaree-residence-nimman-soi-15-3.jpg",
      "images/ravvaree-residence-nimman-soi-15-4.jpg",
      "images/ravvaree-residence-nimman-soi-15-5.jpg",
      "images/ravvaree-residence-nimman-soi-15-6.jpg",
      "images/ravvaree-residence-nimman-soi-15-7.jpg",
      "images/ravvaree-residence-nimman-soi-15-8.jpg",
      "images/ravvaree-residence-nimman-soi-15-9.jpg",
      "images/ravvaree-residence-nimman-soi-15-10.jpg",
      "images/ravvaree-residence-nimman-soi-15-11.jpg",
      "images/ravvaree-residence-nimman-soi-15-12.jpg",
      "images/ravvaree-residence-nimman-soi-15-13.jpg",
      "images/ravvaree-residence-nimman-soi-15-14.jpg",
      "images/ravvaree-residence-nimman-soi-15-15.jpg",
      "images/ravvaree-residence-nimman-soi-15-16.jpg",
      "images/ravvaree-residence-nimman-soi-15-17.jpg",
      "images/ravvaree-residence-nimman-soi-15-18.jpg",
      "images/ravvaree-residence-nimman-soi-15-19.jpg",
      "images/ravvaree-residence-nimman-soi-15-20.jpg"
    ]
  },
  {
    "id": "CM-0004",
    "title": "Viengping Mansion Room 1008-9 (10th floor)",
    "city": "Chiang Mai",
    "type": "Condo",
    "deal": "Sale",
    "status": "Available",
    "price": "4.69 MB",
    "bedrooms": "2 Bedrooms",
    "bathrooms": "2 Bathrooms",
    "area": "71 sq.m",
    "room": "Room 1008-9",
    "floor": "10th floor",
    "map": "https://maps.app.goo.gl/cHi4XGUstCAHv3uCA",
    "description": "Viengping Mansion Room 1008-9 (10th floor). 2Bedroom 2 Bathrooms. Area 71 sq.m. Room 1008-9 10th floor.",
    "highlights": [
      "2 Bedrooms",
      "2 Bathrooms",
      "71 sq.m",
      "10th floor",
      "Room 1008-9"
    ],
    "images": [
      "images/viengping-mansion-1.jpg",
      "images/viengping-mansion-2.jpg",
      "images/viengping-mansion-3.jpg",
      "images/viengping-mansion-4.jpg",
      "images/viengping-mansion-5.jpg",
      "images/viengping-mansion-6.jpg",
      "images/viengping-mansion-7.jpg",
      "images/viengping-mansion-8.jpg",
      "images/viengping-mansion-9.jpg",
      "images/viengping-mansion-10.jpg",
      "images/viengping-mansion-11.jpg",
      "images/viengping-mansion-12.jpg",
      "images/viengping-mansion-13.jpg",
      "images/viengping-mansion-14.jpg",
      "images/viengping-mansion-15.jpg",
      "images/viengping-mansion-16.jpg",
      "images/viengping-mansion-17.jpg",
      "images/viengping-mansion-18.jpg",
      "images/viengping-mansion-19.jpg",
      "images/viengping-mansion-20.jpg"
    ]
  },
  {
    "id": "CM-0005",
    "title": "Hillside Plaza & Condotel 4 Room 808 (8th Floor)",
    "city": "Chiang Mai",
    "type": "Condo",
    "deal": "Sale",
    "status": "Available",
    "price": "5.69 MB",
    "bedrooms": "2 Bedrooms",
    "bathrooms": "2 Bathrooms",
    "area": "78.7 sq.m.",
    "room": "Room  808",
    "floor": "8th Floor",
    "map": "https://maps.app.goo.gl/KirnqeC8Nzdeubki9",
    "description": "Hillside Plaza & Condotel 4 Room 808 (8th Floor). 2Bedroom 2 Bathrooms | 2 Large Balconies with Open View. Area 78.7 sq.m. Room  808 8th Floor.",
    "highlights": [
      "2 Bedrooms",
      "2 Bathrooms",
      "78.7 sq.m.",
      "8th Floor",
      "Room  808",
      "2 Large Balconies with Open View"
    ],
    "images": [
      "images/hillside-plaza-condotel-4-1.jpg",
      "images/hillside-plaza-condotel-4-2.jpg",
      "images/hillside-plaza-condotel-4-3.jpg",
      "images/hillside-plaza-condotel-4-4.jpg",
      "images/hillside-plaza-condotel-4-5.jpg",
      "images/hillside-plaza-condotel-4-6.jpg",
      "images/hillside-plaza-condotel-4-7.jpg",
      "images/hillside-plaza-condotel-4-8.jpg",
      "images/hillside-plaza-condotel-4-9.jpg",
      "images/hillside-plaza-condotel-4-10.jpg",
      "images/hillside-plaza-condotel-4-11.jpg",
      "images/hillside-plaza-condotel-4-12.jpg",
      "images/hillside-plaza-condotel-4-13.jpg",
      "images/hillside-plaza-condotel-4-14.jpg",
      "images/hillside-plaza-condotel-4-15.jpg",
      "images/hillside-plaza-condotel-4-16.jpg",
      "images/hillside-plaza-condotel-4-17.jpg",
      "images/hillside-plaza-condotel-4-18.jpg",
      "images/hillside-plaza-condotel-4-19.jpg",
      "images/hillside-plaza-condotel-4-20.jpg"
    ]
  },
  {
    "id": "CM-0006",
    "title": "Ravvaree Residence nimman soi 15 Room 318 (3rd Floor)",
    "city": "Chiang Mai",
    "type": "Condo",
    "deal": "Sale",
    "status": "Available",
    "price": "6.59 MB",
    "bedrooms": "1 Bedroom",
    "bathrooms": "1 Bathroom",
    "area": "71.36 sq.m.",
    "room": "Room 318",
    "floor": "3rd Floor",
    "map": "https://maps.app.goo.gl/Hcpno7c57fefWAnYA",
    "description": "Ravvaree Residence nimman soi 15 Room 318 (3rd Floor). 1 Bed Room /1 bath Room | 2 Large Balconies with Mountain View. Area 71.36 sq.m. Room 318 3rd Floor.",
    "highlights": [
      "1 Bedroom",
      "1 Bathroom",
      "71.36 sq.m.",
      "3rd Floor",
      "Room 318",
      "2 Large Balconies with Mountain View"
    ],
    "images": [
      "images/ravvaree-residence-room-318-1.jpg",
      "images/ravvaree-residence-room-318-2.jpg",
      "images/ravvaree-residence-room-318-3.jpg",
      "images/ravvaree-residence-room-318-4.jpg",
      "images/ravvaree-residence-room-318-5.jpg",
      "images/ravvaree-residence-room-318-6.jpg",
      "images/ravvaree-residence-room-318-7.jpg",
      "images/ravvaree-residence-room-318-8.jpg",
      "images/ravvaree-residence-room-318-9.jpg",
      "images/ravvaree-residence-room-318-10.jpg",
      "images/ravvaree-residence-room-318-11.jpg",
      "images/ravvaree-residence-room-318-12.jpg",
      "images/ravvaree-residence-room-318-13.jpg",
      "images/ravvaree-residence-room-318-14.jpg",
      "images/ravvaree-residence-room-318-15.jpg",
      "images/ravvaree-residence-room-318-16.jpg",
      "images/ravvaree-residence-room-318-17.jpg",
      "images/ravvaree-residence-room-318-18.jpg",
      "images/ravvaree-residence-room-318-19.jpg",
      "images/ravvaree-residence-room-318-20.jpg"
    ]
  },
  {
    "id": "CM-0007",
    "title": "Tree Boutique Condo Nimman Room 501 (5th Floor)",
    "city": "Chiang Mai",
    "type": "Condo",
    "deal": "Sale",
    "status": "Available",
    "price": "2.49 MB",
    "bedrooms": "1 Bedroom",
    "bathrooms": "-",
    "area": "25.14 SQ.M.",
    "room": "Room 501",
    "floor": "5th Floor",
    "map": "https://maps.app.goo.gl/hqBm5CvckQv5ogKU9?g_st=ipc",
    "description": "Tree Boutique Condo Nimman Room 501 (5th Floor). 1 Bedroom with Balcony. Area 25.14 SQ.M. Room 501 5th Floor.",
    "highlights": [
      "1 Bedroom",
      "25.14 SQ.M.",
      "5th Floor",
      "Room 501"
    ],
    "images": [
      "images/tree-boutique-condo-nimman-room-501-5th-floor-25-14-sq-m-1.jpg",
      "images/tree-boutique-condo-nimman-room-501-5th-floor-25-14-sq-m-2.jpg",
      "images/tree-boutique-condo-nimman-room-501-5th-floor-25-14-sq-m-3.jpg",
      "images/tree-boutique-condo-nimman-room-501-5th-floor-25-14-sq-m-4.jpg",
      "images/tree-boutique-condo-nimman-room-501-5th-floor-25-14-sq-m-5.jpg",
      "images/tree-boutique-condo-nimman-room-501-5th-floor-25-14-sq-m-6.jpg",
      "images/tree-boutique-condo-nimman-room-501-5th-floor-25-14-sq-m-7.jpg",
      "images/tree-boutique-condo-nimman-room-501-5th-floor-25-14-sq-m-8.jpg",
      "images/tree-boutique-condo-nimman-room-501-5th-floor-25-14-sq-m-9.jpg",
      "images/tree-boutique-condo-nimman-room-501-5th-floor-25-14-sq-m-10.jpg",
      "images/tree-boutique-condo-nimman-room-501-5th-floor-25-14-sq-m-11.jpg",
      "images/tree-boutique-condo-nimman-room-501-5th-floor-25-14-sq-m-12.jpg",
      "images/tree-boutique-condo-nimman-room-501-5th-floor-25-14-sq-m-13.jpg",
      "images/tree-boutique-condo-nimman-room-501-5th-floor-25-14-sq-m-14.jpg",
      "images/tree-boutique-condo-nimman-room-501-5th-floor-25-14-sq-m-15.jpg",
      "images/tree-boutique-condo-nimman-room-501-5th-floor-25-14-sq-m-16.jpg",
      "images/tree-boutique-condo-nimman-room-501-5th-floor-25-14-sq-m-17.jpg",
      "images/tree-boutique-condo-nimman-room-501-5th-floor-25-14-sq-m-18.jpg",
      "images/tree-boutique-condo-nimman-room-501-5th-floor-25-14-sq-m-19.jpg",
      "images/tree-boutique-condo-nimman-room-501-5th-floor-25-14-sq-m-20.jpg"
    ]
  },
  {
    "id": "CM-0008",
    "title": "Tarntip Garden Place Condominium Room 2215 (6th Floor Building 2)",
    "city": "Chiang Mai",
    "type": "Condo",
    "deal": "Sale",
    "status": "Available",
    "price": "1.89 MB",
    "bedrooms": "1 Bedroom",
    "bathrooms": "-",
    "area": "23.39 SQ.M.",
    "room": "Room 2215",
    "floor": "6th Floor  Building 2",
    "map": "https://maps.app.goo.gl/syBosrCG2KjRZB3N7",
    "description": "Tarntip Garden Place Condominium Room 2215 (6th Floor Building 2). 1Bedroom. Area 23.39 SQ.M. Room 2215 6th Floor  Building 2.",
    "highlights": [
      "1 Bedroom",
      "23.39 SQ.M.",
      "6th Floor  Building 2",
      "Room 2215"
    ],
    "images": [
      "images/tarntip-garden-place-condo-room-2215-2nd-floor-1.jpg",
      "images/tarntip-garden-place-condo-room-2215-2nd-floor-2.jpg",
      "images/tarntip-garden-place-condo-room-2215-2nd-floor-3.jpg",
      "images/tarntip-garden-place-condo-room-2215-2nd-floor-4.jpg",
      "images/tarntip-garden-place-condo-room-2215-2nd-floor-5.jpg",
      "images/tarntip-garden-place-condo-room-2215-2nd-floor-6.jpg",
      "images/tarntip-garden-place-condo-room-2215-2nd-floor-7.jpg",
      "images/tarntip-garden-place-condo-room-2215-2nd-floor-8.jpg",
      "images/tarntip-garden-place-condo-room-2215-2nd-floor-9.jpg",
      "images/tarntip-garden-place-condo-room-2215-2nd-floor-10.jpg",
      "images/tarntip-garden-place-condo-room-2215-2nd-floor-11.jpg",
      "images/tarntip-garden-place-condo-room-2215-2nd-floor-12.jpg",
      "images/tarntip-garden-place-condo-room-2215-2nd-floor-13.jpg",
      "images/tarntip-garden-place-condo-room-2215-2nd-floor-14.jpg",
      "images/tarntip-garden-place-condo-room-2215-2nd-floor-15.jpg",
      "images/tarntip-garden-place-condo-room-2215-2nd-floor-16.jpg",
      "images/tarntip-garden-place-condo-room-2215-2nd-floor-17.jpg",
      "images/tarntip-garden-place-condo-room-2215-2nd-floor-18.jpg",
      "images/tarntip-garden-place-condo-room-2215-2nd-floor-19.jpg",
      "images/tarntip-garden-place-condo-room-2215-2nd-floor-20.jpg"
    ]
  },
  {
    "id": "CM-0009",
    "title": "One Plus Klong Chon 2 Room 610 (6th Floor)",
    "city": "Chiang Mai",
    "type": "Condo",
    "deal": "Sale",
    "status": "Available",
    "price": "2.79 MB",
    "bedrooms": "1 Bedroom",
    "bathrooms": "-",
    "area": "30.12 SQ.M.",
    "room": "Room 610",
    "floor": "6th Floor",
    "map": "https://maps.app.goo.gl/L6XxiBt3AgjdXY639",
    "description": "One Plus Klong Chon 2 Room 610 (6th Floor). 1Bedroom | Pool View • Mountain View. Area 30.12 SQ.M. Room 610 6th Floor.",
    "highlights": [
      "1 Bedroom",
      "30.12 SQ.M.",
      "6th Floor",
      "Room 610",
      "Pool View • Mountain View"
    ],
    "images": [
      "images/one-plus-klong-chon-2-room-610-6th-floor-30-12-sq-m-1.jpg",
      "images/one-plus-klong-chon-2-room-610-6th-floor-30-12-sq-m-2.jpg",
      "images/one-plus-klong-chon-2-room-610-6th-floor-30-12-sq-m-3.jpg",
      "images/one-plus-klong-chon-2-room-610-6th-floor-30-12-sq-m-4.jpg",
      "images/one-plus-klong-chon-2-room-610-6th-floor-30-12-sq-m-5.jpg",
      "images/one-plus-klong-chon-2-room-610-6th-floor-30-12-sq-m-6.jpg",
      "images/one-plus-klong-chon-2-room-610-6th-floor-30-12-sq-m-7.jpg",
      "images/one-plus-klong-chon-2-room-610-6th-floor-30-12-sq-m-8.jpg",
      "images/one-plus-klong-chon-2-room-610-6th-floor-30-12-sq-m-9.jpg",
      "images/one-plus-klong-chon-2-room-610-6th-floor-30-12-sq-m-10.jpg",
      "images/one-plus-klong-chon-2-room-610-6th-floor-30-12-sq-m-11.jpg",
      "images/one-plus-klong-chon-2-room-610-6th-floor-30-12-sq-m-12.jpg",
      "images/one-plus-klong-chon-2-room-610-6th-floor-30-12-sq-m-13.jpg",
      "images/one-plus-klong-chon-2-room-610-6th-floor-30-12-sq-m-14.jpg",
      "images/one-plus-klong-chon-2-room-610-6th-floor-30-12-sq-m-15.jpg",
      "images/one-plus-klong-chon-2-room-610-6th-floor-30-12-sq-m-16.jpg",
      "images/one-plus-klong-chon-2-room-610-6th-floor-30-12-sq-m-17.jpg",
      "images/one-plus-klong-chon-2-room-610-6th-floor-30-12-sq-m-18.jpg",
      "images/one-plus-klong-chon-2-room-610-6th-floor-30-12-sq-m-19.jpg",
      "images/one-plus-klong-chon-2-room-610-6th-floor-30-12-sq-m-20.jpg"
    ]
  },
  {
    "id": "CM-0010",
    "title": "Chomdoi Condominium (Square Building) Room 131 (2th Floor)",
    "city": "Chiang Mai",
    "type": "Condo",
    "deal": "Sale",
    "status": "Available",
    "price": "2,49MB",
    "bedrooms": "1 Bedroom",
    "bathrooms": "-",
    "area": "35 SQ.M.",
    "room": "Room 131",
    "floor": "2th Floor",
    "map": "https://maps.app.goo.gl/JPuQD66ZRyjEGogp7?g_st=ac",
    "description": "Chomdoi Condominium (Square Building) Room 131 (2th Floor). 1Bedroom | Balcony. Area 35 SQ.M. Room 131 2th Floor.",
    "highlights": [
      "1 Bedroom",
      "35 SQ.M.",
      "2th Floor",
      "Room 131",
      "Balcony"
    ],
    "images": [
      "images/chomdoi-condo-unit-131-2nd-floor-1.jpg",
      "images/chomdoi-condo-unit-131-2nd-floor-2.jpg",
      "images/chomdoi-condo-unit-131-2nd-floor-3.jpg",
      "images/chomdoi-condo-unit-131-2nd-floor-4.jpg",
      "images/chomdoi-condo-unit-131-2nd-floor-5.jpg",
      "images/chomdoi-condo-unit-131-2nd-floor-6.jpg",
      "images/chomdoi-condo-unit-131-2nd-floor-7.jpg",
      "images/chomdoi-condo-unit-131-2nd-floor-8.jpg",
      "images/chomdoi-condo-unit-131-2nd-floor-9.jpg",
      "images/chomdoi-condo-unit-131-2nd-floor-10.jpg",
      "images/chomdoi-condo-unit-131-2nd-floor-11.jpg",
      "images/chomdoi-condo-unit-131-2nd-floor-12.jpg",
      "images/chomdoi-condo-unit-131-2nd-floor-13.jpg",
      "images/chomdoi-condo-unit-131-2nd-floor-14.jpg",
      "images/chomdoi-condo-unit-131-2nd-floor-15.jpg",
      "images/chomdoi-condo-unit-131-2nd-floor-16.jpg",
      "images/chomdoi-condo-unit-131-2nd-floor-17.jpg",
      "images/chomdoi-condo-unit-131-2nd-floor-18.jpg",
      "images/chomdoi-condo-unit-131-2nd-floor-19.jpg",
      "images/chomdoi-condo-unit-131-2nd-floor-20.jpg"
    ]
  },
  {
    "id": "CM-0011",
    "title": "Chomdoi Condo Room 903 (9th Floor)",
    "city": "Chiang Mai",
    "type": "Condo",
    "deal": "Sale",
    "status": "Available",
    "price": "2.75 MB",
    "bedrooms": "1 Bedroom",
    "bathrooms": "-",
    "area": "35 SQ.M.",
    "room": "Room 903",
    "floor": "9th Floor",
    "map": "https://maps.app.goo.gl/JPuQD66ZRyjEGogp7?g_st=ac",
    "description": "Chomdoi Condo Room 903 (9th Floor). 1 Bedroom. Area 35 SQ.M. Room 903 9th Floor.",
    "highlights": [
      "1 Bedroom",
      "35 SQ.M.",
      "9th Floor",
      "Room 903"
    ],
    "images": [
      "images/chomdoi-condo-room-903-9-floor-1.jpg",
      "images/chomdoi-condo-room-903-9-floor-2.jpg",
      "images/chomdoi-condo-room-903-9-floor-3.jpg",
      "images/chomdoi-condo-room-903-9-floor-4.jpg",
      "images/chomdoi-condo-room-903-9-floor-5.jpg",
      "images/chomdoi-condo-room-903-9-floor-6.jpg",
      "images/chomdoi-condo-room-903-9-floor-7.jpg",
      "images/chomdoi-condo-room-903-9-floor-8.jpg",
      "images/chomdoi-condo-room-903-9-floor-9.jpg",
      "images/chomdoi-condo-room-903-9-floor-10.jpg",
      "images/chomdoi-condo-room-903-9-floor-11.jpg",
      "images/chomdoi-condo-room-903-9-floor-12.jpg",
      "images/chomdoi-condo-room-903-9-floor-13.jpg",
      "images/chomdoi-condo-room-903-9-floor-14.jpg",
      "images/chomdoi-condo-room-903-9-floor-15.jpg",
      "images/chomdoi-condo-room-903-9-floor-16.jpg",
      "images/chomdoi-condo-room-903-9-floor-17.jpg",
      "images/chomdoi-condo-room-903-9-floor-18.jpg",
      "images/chomdoi-condo-room-903-9-floor-19.jpg",
      "images/chomdoi-condo-room-903-9-floor-20.jpg"
    ]
  },
  {
    "id": "CM-0012",
    "title": "Ruen Come Tower Room 607 (6th Floor)",
    "city": "Chiang Mai",
    "type": "Condo",
    "deal": "Sale",
    "status": "Available",
    "price": "2.29 MB",
    "bedrooms": "1 Bedroom",
    "bathrooms": "-",
    "area": "30.42 sq.m.",
    "room": "Room 607",
    "floor": "6th Floor",
    "map": "https://maps.app.goo.gl/ZmDRq5w29YyguAU3A?g_st=ac",
    "description": "Ruen Come Tower Room 607 (6th Floor). 1 Bedroom. Area 30.42 sq.m. Room 607 6th Floor.",
    "highlights": [
      "1 Bedroom",
      "30.42 sq.m.",
      "6th Floor",
      "Room 607"
    ],
    "images": [
      "images/ruen-come-tower-room-607-6th-floor-1.jpg",
      "images/ruen-come-tower-room-607-6th-floor-2.jpg",
      "images/ruen-come-tower-room-607-6th-floor-3.jpg",
      "images/ruen-come-tower-room-607-6th-floor-4.jpg",
      "images/ruen-come-tower-room-607-6th-floor-5.jpg",
      "images/ruen-come-tower-room-607-6th-floor-6.jpg",
      "images/ruen-come-tower-room-607-6th-floor-7.jpg",
      "images/ruen-come-tower-room-607-6th-floor-8.jpg",
      "images/ruen-come-tower-room-607-6th-floor-9.jpg",
      "images/ruen-come-tower-room-607-6th-floor-10.jpg",
      "images/ruen-come-tower-room-607-6th-floor-11.jpg"
    ]
  },
  {
    "id": "CM-0013",
    "title": "One Plus Klong Chol 3 Condominium Room 704 (7th floor)",
    "city": "Chiang Mai",
    "type": "Condo",
    "deal": "Sale",
    "status": "Available",
    "price": "2.89 MB",
    "bedrooms": "1 Bedroom",
    "bathrooms": "-",
    "area": "30.49 SQ.M.",
    "room": "Room 704",
    "floor": "7th floor",
    "map": "https://maps.app.goo.gl/L6XxiBt3AgjdXY639",
    "description": "One Plus Klong Chol 3 Condominium Room 704 (7th floor). 1Bedroom. Area 30.49 SQ.M. Room 704 7th floor.",
    "highlights": [
      "1 Bedroom",
      "30.49 SQ.M.",
      "7th floor",
      "Room 704"
    ],
    "images": [
      "images/one-plus-klong-chol-3-condo-room704-1.jpg",
      "images/one-plus-klong-chol-3-condo-room704-2.jpg",
      "images/one-plus-klong-chol-3-condo-room704-3.jpg",
      "images/one-plus-klong-chol-3-condo-room704-4.jpg",
      "images/one-plus-klong-chol-3-condo-room704-5.jpg",
      "images/one-plus-klong-chol-3-condo-room704-6.jpg",
      "images/one-plus-klong-chol-3-condo-room704-7.jpg",
      "images/one-plus-klong-chol-3-condo-room704-8.jpg",
      "images/one-plus-klong-chol-3-condo-room704-9.jpg",
      "images/one-plus-klong-chol-3-condo-room704-10.jpg",
      "images/one-plus-klong-chol-3-condo-room704-11.jpg",
      "images/one-plus-klong-chol-3-condo-room704-12.jpg",
      "images/one-plus-klong-chol-3-condo-room704-13.jpg",
      "images/one-plus-klong-chol-3-condo-room704-14.jpg",
      "images/one-plus-klong-chol-3-condo-room704-15.jpg",
      "images/one-plus-klong-chol-3-condo-room704-16.jpg",
      "images/one-plus-klong-chol-3-condo-room704-17.jpg",
      "images/one-plus-klong-chol-3-condo-room704-18.jpg",
      "images/one-plus-klong-chol-3-condo-room704-19.jpg",
      "images/one-plus-klong-chol-3-condo-room704-20.jpg"
    ]
  },
  {
    "id": "CM-0014",
    "title": "WIANGPING MANSION Room 612-613 (6th Floor)",
    "city": "Chiang Mai",
    "type": "Condo",
    "deal": "Sale",
    "status": "Sold Out",
    "price": "4.99 MB",
    "bedrooms": "2 Bedrooms",
    "bathrooms": "-",
    "area": "78.5 SQ.M.",
    "room": "Room 612-613",
    "floor": "6th Floor",
    "map": "https://maps.app.goo.gl/cHi4XGUstCAHv3uCA",
    "description": "WIANGPING MANSION Room 612-613 (6th Floor). 2 Bedrooms. Area 78.5 SQ.M. Room 612-613 6th Floor.",
    "highlights": [
      "2 Bedrooms",
      "78.5 SQ.M.",
      "6th Floor",
      "Room 612-613"
    ],
    "images": [
      "images/wiangping-mansion-room-612-613-6th-floor-1.jpg",
      "images/wiangping-mansion-room-612-613-6th-floor-2.jpg",
      "images/wiangping-mansion-room-612-613-6th-floor-3.jpg",
      "images/wiangping-mansion-room-612-613-6th-floor-4.jpg",
      "images/wiangping-mansion-room-612-613-6th-floor-5.jpg",
      "images/wiangping-mansion-room-612-613-6th-floor-6.jpg",
      "images/wiangping-mansion-room-612-613-6th-floor-7.jpg",
      "images/wiangping-mansion-room-612-613-6th-floor-8.jpg",
      "images/wiangping-mansion-room-612-613-6th-floor-9.jpg",
      "images/wiangping-mansion-room-612-613-6th-floor-10.jpg",
      "images/wiangping-mansion-room-612-613-6th-floor-11.jpg",
      "images/wiangping-mansion-room-612-613-6th-floor-12.jpg",
      "images/wiangping-mansion-room-612-613-6th-floor-13.jpg",
      "images/wiangping-mansion-room-612-613-6th-floor-14.jpg",
      "images/wiangping-mansion-room-612-613-6th-floor-15.jpg",
      "images/wiangping-mansion-room-612-613-6th-floor-16.jpg",
      "images/wiangping-mansion-room-612-613-6th-floor-17.jpg",
      "images/wiangping-mansion-room-612-613-6th-floor-18.jpg",
      "images/wiangping-mansion-room-612-613-6th-floor-19.jpg",
      "images/wiangping-mansion-room-612-613-6th-floor-20.jpg"
    ]
  },
  {
    "id": "CM-0015",
    "title": "The Next 1.3 Unit 3609 (3rd Floor)",
    "city": "Chiang Mai",
    "type": "Condo",
    "deal": "Sale",
    "status": "Available",
    "price": "3.69 MB",
    "bedrooms": "2 Bedrooms",
    "bathrooms": "-",
    "area": "61.48 SQ.M.",
    "room": "Unit 3609",
    "floor": "3rd Floor",
    "map": "https://maps.app.goo.gl/85u98y3mHX4VasbG7",
    "description": "The Next 1.3 Unit 3609 (3rd Floor). 2 Bedrooms. Area 61.48 SQ.M. Unit 3609 3rd Floor.",
    "highlights": [
      "2 Bedrooms",
      "61.48 SQ.M.",
      "3rd Floor",
      "Unit 3609"
    ],
    "images": [
      "images/the-next-1-1.jpg",
     "images/the-next-1-26.jpg",
      "images/the-next-1-27.jpg",
      "images/the-next-1-28.jpg",
      "images/the-next-1-29.jpg",
      "images/the-next-1-30.jpg",
      "images/the-next-1-31.jpg",
      "images/the-next-1-32.jpg",
      "images/the-next-1-33.jpg",
      "images/the-next-1-34.jpg",
      "images/the-next-1-35.jpg",
      "images/the-next-1-36.jpg",
      "images/the-next-1-37.jpg",
      "images/the-next-1-38.jpg",
      "images/the-next-1-39.jpg",
      "images/the-next-1-40.jpg",
      "images/the-next-1-41.jpg",
      "images/the-next-1-42.jpg",
      "images/the-next-1-43.jpg",
      "images/the-next-1-44.jpg"
    ]
  },
  {
    "id": "CM-0016",
    "title": "103 Condominium 3 Unit 516 5th Floor",
    "city": "Chiang Mai",
    "type": "Condo",
    "deal": "Sale",
    "status": "Available",
    "price": "2.19 MB",
    "bedrooms": "1 Bedroom",
    "bathrooms": "-",
    "area": "24.5 SQ.M.",
    "room": "Unit 516",
    "floor": "5th Floor",
    "map": "https://maps.app.goo.gl/oWSjiCTVGQxvH4aHA",
    "description": "103 Condominium 3 Unit 516 5th Floor. 1 Bedroom. Area 24.5 SQ.M. Unit 516 5th Floor.",
    "highlights": [
      "1 Bedroom",
      "24.5 SQ.M.",
      "5th Floor",
      "Unit 516"
    ],
    "images": [
      "images/103-condo-3-unit-516-5th-floor-1.jpg",
      "images/103-condo-3-unit-516-5th-floor-2.jpg",
      "images/103-condo-3-unit-516-5th-floor-3.jpg",
      "images/103-condo-3-unit-516-5th-floor-4.jpg",
      "images/103-condo-3-unit-516-5th-floor-5.jpg",
      "images/103-condo-3-unit-516-5th-floor-6.jpg",
      "images/103-condo-3-unit-516-5th-floor-7.jpg",
      "images/103-condo-3-unit-516-5th-floor-8.jpg",
      "images/103-condo-3-unit-516-5th-floor-9.jpg",
      "images/103-condo-3-unit-516-5th-floor-10.jpg",
      "images/103-condo-3-unit-516-5th-floor-11.jpg",
      "images/103-condo-3-unit-516-5th-floor-12.jpg",
      "images/103-condo-3-unit-516-5th-floor-13.jpg",
      "images/103-condo-3-unit-516-5th-floor-14.jpg"
    ]
  },
  {
    "id": "CM-0017",
    "title": "Rawiwari Residence Unit 201, 2nd Floor",
    "city": "Chiang Mai",
    "type": "Condo",
    "deal": "Sale",
    "status": "Available",
    "price": "6.59 MB",
    "bedrooms": "2 Bedrooms",
    "bathrooms": "-",
    "area": "76.26 SQ.M.",
    "room": "Unit 201",
    "floor": "2nd Floor",
    "map": "https://maps.app.goo.gl/Hcpno7c57fefWAnYA",
    "description": "Rawiwari Residence Unit 201, 2nd Floor. 2 Bedrooms | 2 Large Balconies. Area 76.26 SQ.M. Unit 201 2nd Floor.",
    "highlights": [
      "2 Bedrooms",
      "76.26 SQ.M.",
      "2nd Floor",
      "Unit 201",
      "2 Large Balconies"
    ],
    "images": [
      "images/raviwari-residence-unit-201-2nd-floor-1.jpg",
      "images/raviwari-residence-unit-201-2nd-floor-2.jpg",
      "images/raviwari-residence-unit-201-2nd-floor-3.jpg",
      "images/raviwari-residence-unit-201-2nd-floor-4.jpg",
      "images/raviwari-residence-unit-201-2nd-floor-5.jpg",
      "images/raviwari-residence-unit-201-2nd-floor-6.jpg",
      "images/raviwari-residence-unit-201-2nd-floor-7.jpg",
      "images/raviwari-residence-unit-201-2nd-floor-8.jpg",
      "images/raviwari-residence-unit-201-2nd-floor-9.jpg",
      "images/raviwari-residence-unit-201-2nd-floor-10.jpg",
      "images/raviwari-residence-unit-201-2nd-floor-11.jpg",
      "images/raviwari-residence-unit-201-2nd-floor-12.jpg",
      "images/raviwari-residence-unit-201-2nd-floor-13.jpg",
      "images/raviwari-residence-unit-201-2nd-floor-14.jpg",
      "images/raviwari-residence-unit-201-2nd-floor-15.jpg",
      "images/raviwari-residence-unit-201-2nd-floor-16.jpg",
      "images/raviwari-residence-unit-201-2nd-floor-17.jpg",
      "images/raviwari-residence-unit-201-2nd-floor-18.jpg",
      "images/raviwari-residence-unit-201-2nd-floor-19.jpg",
      "images/raviwari-residence-unit-201-2nd-floor-20.jpg"
    ]
  },
  {
    "id": "CM-0018",
    "title": "Siriporn Don Chan Village, Soi 15",
    "city": "Chiang Mai",
    "type": "House",
    "deal": "Sale",
    "status": "Available",
    "price": "9.89 MB",
    "bedrooms": "4 Bedrooms",
    "bathrooms": "-",
    "area": "74 sq.wah",
    "room": "Soi 15",
    "floor": "",
    "map": "",
    "description": "Siriporn Don Chan Village, Soi 15. 4 Bedrooms. Area 74 sq.wah. Soi 15 .",
    "highlights": [
      "4 Bedrooms",
      "74 sq.wah",
      "Soi 15"
    ],
    "images": [
      "images/siriporn-don-chan-village-1.jpg",
      "images/siriporn-don-chan-village-2.jpg",
      "images/siriporn-don-chan-village-3.jpg",
      "images/siriporn-don-chan-village-4.jpg",
      "images/siriporn-don-chan-village-5.jpg",
      "images/siriporn-don-chan-village-6.jpg",
      "images/siriporn-don-chan-village-7.jpg",
      "images/siriporn-don-chan-village-8.jpg"
    ]
  },
  {
    "id": "CM-0019",
    "title": "Siwalee Klong Chol House No. Soi 27 (211/190,)",
    "city": "Chiang Mai",
    "type": "House",
    "deal": "Sale",
    "status": "Available",
    "price": "9.99 MB",
    "bedrooms": "4 Bedrooms",
    "bathrooms": "-",
    "area": "61.6 Sq.Wah Usable Area: 250 Sq.M.",
    "room": "Soi 27",
    "floor": "211/190,",
    "map": "https://maps.app.goo.gl/yPM5qz9by9yBNaka6",
    "description": "Siwalee Klong Chol House No. Soi 27 (211/190,). 4 Bedrooms | Private Swimming Pool with Jacuzzi. Area 61.6 Sq.Wah Usable Area: 250 Sq.M. Soi 27 211/190,.",
    "highlights": [
      "4 Bedrooms",
      "61.6 Sq.Wah Usable Area: 250 Sq.M.",
      "211/190,",
      "Soi 27",
      "Private Swimming Pool with Jacuzzi"
    ],
    "images": [
      "images/siwalee-klong-chol-house-no-211190-soi-27-1.jpg",
      "images/siwalee-klong-chol-house-no-211190-soi-27-2.jpg",
      "images/siwalee-klong-chol-house-no-211190-soi-27-3.jpg",
      "images/siwalee-klong-chol-house-no-211190-soi-27-4.jpg",
      "images/siwalee-klong-chol-house-no-211190-soi-27-5.jpg",
      "images/siwalee-klong-chol-house-no-211190-soi-27-6.jpg",
      "images/siwalee-klong-chol-house-no-211190-soi-27-7.jpg",
      "images/siwalee-klong-chol-house-no-211190-soi-27-8.jpg",
      "images/siwalee-klong-chol-house-no-211190-soi-27-9.jpg",
      "images/siwalee-klong-chol-house-no-211190-soi-27-10.jpg",
      "images/siwalee-klong-chol-house-no-211190-soi-27-11.jpg",
      "images/siwalee-klong-chol-house-no-211190-soi-27-12.jpg",
      "images/siwalee-klong-chol-house-no-211190-soi-27-13.jpg",
      "images/siwalee-klong-chol-house-no-211190-soi-27-14.jpg",
      "images/siwalee-klong-chol-house-no-211190-soi-27-15.jpg",
      "images/siwalee-klong-chol-house-no-211190-soi-27-16.jpg",
      "images/siwalee-klong-chol-house-no-211190-soi-27-17.jpg",
      "images/siwalee-klong-chol-house-no-211190-soi-27-18.jpg"
    ]
  },
  {
    "id": "CM-0020",
    "title": "JC Hill Place Room 909 (9th Floor)",
    "city": "Chiang Mai",
    "type": "Condo",
    "deal": "Sale",
    "status": "Available",
    "price": "2.39 MB",
    "bedrooms": "-",
    "bathrooms": "-",
    "area": "32.09 m²",
    "room": "Room 909",
    "floor": "9th Floor",
    "map": "https://maps.app.goo.gl/oP2Y8N1k6XxqgA5M7",
    "description": "JC Hill Place Room 909 (9th Floor). 1 /bedroom | Geniş Balkon. Area 32.09 m². Room 909 9th Floor.",
    "highlights": [
      "32.09 m²",
      "9th Floor",
      "Room 909",
      "Geniş Balkon"
    ],
    "images": [
      "images/jc-hill-place-909-1.jpg",
      "images/jc-hill-place-909-2.jpg",
      "images/jc-hill-place-909-3.jpg",
      "images/jc-hill-place-909-4.jpg",
      "images/jc-hill-place-909-5.jpg",
      "images/jc-hill-place-909-6.jpg",
      "images/jc-hill-place-909-7.jpg",
      "images/jc-hill-place-909-8.jpg",
      "images/jc-hill-place-909-9.jpg",
      "images/jc-hill-place-909-10.jpg",
      "images/jc-hill-place-909-11.jpg",
      "images/jc-hill-place-909-12.jpg",
      "images/jc-hill-place-909-13.jpg",
      "images/jc-hill-place-909-14.jpg",
      "images/jc-hill-place-909-15.jpg",
      "images/jc-hill-place-909-16.jpg",
      "images/jc-hill-place-909-17.jpg",
      "images/jc-hill-place-909-18.jpg",
      "images/jc-hill-place-909-19.jpg",
      "images/jc-hill-place-909-20.jpg",
      "images/jc-hill-place-909-21.jpg",
      "images/jc-hill-place-909-22.jpg",
      "images/jc-hill-place-909-23.jpg",
      "images/jc-hill-place-909-24.jpg",
      "images/jc-hill-place-909-25.jpg",
      "images/jc-hill-place-909-26.jpg",
      "images/jc-hill-place-909-27.jpg",
      "images/jc-hill-place-909-28.jpg",
      "images/jc-hill-place-909-29.jpg",
      "images/jc-hill-place-909-30.jpg"
    ]
  },
  {
    "id": "CM-0021",
    "title": "Wiang Ping Mansion Condominium Unit 1110 (11th Floor)",
    "city": "Chiang Mai",
    "type": "Condo",
    "deal": "Sale",
    "status": "Available",
    "price": "2.59 MB",
    "bedrooms": "1 Bedroom",
    "bathrooms": "-",
    "area": "36 sq.m",
    "room": "Unit 1110",
    "floor": "11th Floor",
    "map": "https://maps.app.goo.gl/cHi4XGUstCAHv3uCA",
    "description": "Wiang Ping Mansion Condominium Unit 1110 (11th Floor). 1 Bedroom. Area 36 sq.m. Unit 1110 11th Floor.",
    "highlights": [
      "1 Bedroom",
      "36 sq.m",
      "11th Floor",
      "Unit 1110"
    ],
    "images": [
      "images/wiang-ping-mansion-condo-1110-1.jpg",
      "images/wiang-ping-mansion-condo-1110-2.jpg",
      "images/wiang-ping-mansion-condo-1110-3.jpg",
      "images/wiang-ping-mansion-condo-1110-4.jpg",
      "images/wiang-ping-mansion-condo-1110-5.jpg",
      "images/wiang-ping-mansion-condo-1110-6.jpg",
      "images/wiang-ping-mansion-condo-1110-7.jpg",
      "images/wiang-ping-mansion-condo-1110-8.jpg",
      "images/wiang-ping-mansion-condo-1110-9.jpg",
      "images/wiang-ping-mansion-condo-1110-10.jpg",
      "images/wiang-ping-mansion-condo-1110-11.jpg",
      "images/wiang-ping-mansion-condo-1110-12.jpg",
      "images/wiang-ping-mansion-condo-1110-13.jpg",
      "images/wiang-ping-mansion-condo-1110-14.jpg",
      "images/wiang-ping-mansion-condo-1110-15.jpg",
      "images/wiang-ping-mansion-condo-1110-16.jpg",
      "images/wiang-ping-mansion-condo-1110-17.jpg",
      "images/wiang-ping-mansion-condo-1110-18.jpg",
      "images/wiang-ping-mansion-condo-1110-19.jpg",
      "images/wiang-ping-mansion-condo-1110-20.jpg",
      "images/wiang-ping-mansion-condo-1110-21.jpg",
      "images/wiang-ping-mansion-condo-1110-22.jpg",
      "images/wiang-ping-mansion-condo-1110-23.jpg",
      "images/wiang-ping-mansion-condo-1110-24.jpg"
    ]
  }
];
